[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "npm install -g pnpm",
  "pnpm config set shamefully-hoist true",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node .output/server/index.mjs"
